
---
- hosts: primary
  tasks:
    - name: Secure local conf file
      replace:
        path: /opt/stack/new/devtsack/local.conf
        regexp: "^{{ item }}=.*$"
        replace: "{{ item }}=*************"
      with_items:
        - 'san_ip'
        - 'san_login'
        - 'san_password'
        - 'cisco_fc_fabric_address'
        - 'cisco_fc_fabric_user'
        - 'cisco_fc_fabric_password'
        - 'cisco_fc_fabric_port'
      ignore_errors: True

    - name: Copy files from {{ ansible_user_dir }} on node
      synchronize:
        src: '{{ ansible_user_dir }}/'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/logs/**
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs
