---

# Run devstack gate
- hosts: all
  vars:
    projects:
      - openstack/cinder
    mds_ip_mapping:
      nodeprovider1: 173.39.89.130
      nodeprovider2: 173.39.89.143
    storage_ip_mapping:
      nodeprovider1: 173.39.89.142
      nodeprovider2: 173.39.89.142
    devstack_local_conf_src: templates/zm_vm_cinder_local_conf.j2
    devstack_gate_env_override:
      DEVSTACK_GATE_TEMPEST_REGEX:
        "test_volumes_actions|test_volume_transfers|test_volume_delete_cascade|AttachVolumeTestJSON"
      TEMPEST_CONCURRENCY: 4
      #DEVSTACK_GATE_UNSTACK: 1
  roles:
    - load-devstack-localconf
    - run-devstack-gate
