---
- hosts: all
  become: true
  tasks:
    - name: Remove python3-pip
      apt: 
        name: python3-pip 
        state: absent
    - name: Remove ansible
      apt:
        name: ansible
        state: absent
    - name: Update apt chache
      apt:
        upgrade: dist
        update_cache: yes
        dpkg_options: 'force-confold,force-confdef'
        cache_valid_time: 4600
      ignore_errors: True


    - name: Install python and mySQL deps
      package:
        name: "{{ item }}"
      with_items:
              #- "python-all-dev"
        - "python-dev"
          #- "python3-all-dev"
        - "python3-dev"
        - "python3-pip"
      ignore_errors: True
    - name: Install storops for python3
      pip:
        name: storops
        executable: pip3
        #- name: Install ansible for python3
        #pip:
        #name: ansible
        #executable: pip3
        #    - name: Remove python3 dist apt pkg python3-simplejson
        #apt:
        #name: python3-simplejson
        #state: absent
        #    - name: Install pip for python3
        #shell: /usr/bin/python3 -m easy_install pip
        #ignore_errors: True
      #- name: Install storops for python3.8
      #shell: /usr/bin/python3.8 -m pip install storops
      #- name: Create symbolic link
      #file:
      #  src: "/usr/bin/python3"
      #  dest: "/usr/bin/python"
      #  state: link
      #- name: Install virtualenv for python3
      #pip:
      #  name: virtualenv
      #  executable: pip3

- hosts: primary
  tasks:
    - name: git clone devstack gate
      git:
        #repo: http://opendev.org/openstack/devstack-gate
        repo: http://github.com/akjayaku/devstack-gate.git
        dest: "{{ workspace }}/devstack-gate"

    - name: check existance of scripts directory
      stat:
        path: "{{ workspace }}/devstack-gate"

    - name: check existance of script
      stat:
        path: "{{ workspace }}/devstack-gate/devstack-vm-gate-wrap.sh"

- hosts: all
  roles:
    - role: fetch-zuul-cloner
      destination: "/usr/zuul-env/bin/zuul-cloner"
      repo_src_dir: "/home/ubuntu/src/opendev.org"
  tasks:
    - name: Create nodepool directory
      file:
        path: /etc/nodepool
        state: directory
        owner: ubuntu
        group: ubuntu
      become: true

    - name: Create nodepool uuid file
      copy:
        dest: /etc/nodepool/uuid
        content: |
          {{ ansible_hostname | to_uuid }}

    - name: Create nodepool sub_nodes file
      copy:
        dest: /etc/nodepool/sub_nodes
        content: ""

    - name: Create nodepool sub_nodes_private file
      copy:
        dest: /etc/nodepool/sub_nodes_private
        content: ""

    - name: Populate nodepool sub_nodes file
      lineinfile:
        path: /etc/nodepool/sub_nodes
        line: "{{ hostvars[item]['nodepool']['public_ipv4'] }}"
      with_items: "{{ groups['subnodes'] }}"
      when: groups['subnodes'] is defined

    - name: Populate nodepool sub_nodes_private file
      lineinfile:
        path: /etc/nodepool/sub_nodes_private
        line: "{{ hostvars[item]['nodepool']['private_ipv4'] }}"
      with_items: "{{ groups['subnodes'] }}"
      when: groups['subnodes'] is defined

    - name: Create nodepool primary file
      copy:
        dest: /etc/nodepool/primary_node_private
        content: "{{ hostvars['primary']['nodepool']['private_ipv4'] }}"
      when: hostvars['primary'] is defined

    - name: Create nodepool node_private for this node
      copy:
        dest: /etc/nodepool/node_private
        content: "{{ nodepool.private_ipv4 }}"

    - name: Copy ssh keys to nodepool directory
      command: "cp .ssh/{{ item }} /etc/nodepool/{{ item }}"
      with_items:
        - id_rsa
        - id_rsa.pub
